# Generated by Django 4.2.5 on 2023-09-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descrção', models.TextField()),
            ],
        ),
    ]
