# Generated by Django 4.2.6 on 2023-10-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231009_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
